### ISSUE TITLE
 "R_stringdist" not resolved from current namespace (stringdist)

### ISSUE THREAD

**Issue by anastasiashukhovaKredi** [markvanderloo/stringdist#73]
Hey all, 
When working with the package, I got this error from time to time:

`Error in .Call("R_stringdist", a, b, method, as.double(weight), as.double(p),  : 
  "R_stringdist" not resolved from current namespace (stringdist)`

Usually restarting R session works, but I am afraid that it might cause problems in the production. Is there any fix? 

Best,
Anastasiia

**Comment by markvanderloo** [comment]
Hi Anastasiia,

Thanks for posting. The same question was asked at #72 and the user seemed to have solved it (at least, the issue was closed some hours after it was opened). I've asked for an update on how it was solved.

Best,
mark

**Comment by ChrisMuir** [comment]
Hey Mark,

Just wanted to add, I've also seen this bug a few times. Always came up while working on `refinr` functions (package that Imports `stringdist`). Steps that would cause it would be running `devtools::load_all("refinr"), then if I tried to run `stringdist::stringdistmatrix()` directly in the same session, I would get this error ( `"R_lower_tri" not resolved from current namespace (stringdist)` ). I would restart R, and then I was able to run `stringdist::stringdistmatrix()` without issues.

I haven't use the workflow above in a few months, so I was seeing this in v0.9.4.6 from CRAN.

**Comment by markvanderloo** [comment]
Strange that you get it back since we haven't updated in a while now. Looking at your list of loaded packages, would it be possible that the maximum number of loaded dll's is reached? (I think it's 100, or used to be anyway).

**Comment by tkstring** [comment]
Hi Mark, I have found the issue can be solved by adding `, PACKAGE="stringdist"` to the `.Call("R_stringdist")` call.

**Comment by markvanderloo** [comment]
Thanks, that's a great find!

**Comment by markvanderloo** [comment]
Done in https://github.com/markvanderloo/stringdist/commit/e648fd8168234064bfe37ee180a19f7fe8abd1a6

**Comment by LUNTSAI** [comment]
> Hi Mark, I have found the issue can be solved by adding `, PACKAGE="stringdist"` to the `.Call("R_stringdist")` call.

Hi, I faced the similar issue like this,
```
model <- catboost.train(learn_pool = train_pool, params = params)

Error in .Call("CatBoostSerializeModel_R", handle) : 
  "CatBoostSerializeModel_R" not resolved from current namespace (catboost)
```
However, I not sure how to add the , PACKAGE = "catboost" into the .Call("CatBoostSerializeModel_R" can you show me how to use it? It would help me a lot.

**Comment by markvanderloo** [comment]
I guess it would be 

```r
.Call("CatBoostSerializeModel_R", handle, PACKAGE="catboost")
```

**Comment by LUNTSAI** [comment]
> ```r
> .Call("CatBoostSerializeModel_R", handle, PACKAGE="catboost")
> ```

Hi, I have tried this in the session before, but either got this or this
```
> .Call("CatBoostSerializeModel_R", handle, PACKAGE = "catboost")
Error: object 'handle' not found

> .Call("CatBoostSerializeModel_R", PACKAGE = "catboost")
Error in .Call("CatBoostSerializeModel_R", PACKAGE = "catboost") : 
  "CatBoostSerializeModel_R" not available for .Call() for package "catboost"
```
Should I add in certain files or anything else?

**Comment by markvanderloo** [comment]
We'll, now your problem is that R cannot find the variable called `handle`.

None of this is related to stringdist though, so I suggest to continue this discussion elsewhere.
